import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer style={{ padding: 16, textAlign: "center" }}>
  <a href="/privacy" style={{ marginRight: 16, fontWeight: 900, color: "#1d4ed8", textDecoration: "none" }}>
    Privacy Policy
  </a>
  <a href="/contact" style={{ fontWeight: 900, color: "#1d4ed8", textDecoration: "none" }}>
    Contact
  </a>
</footer>
      </body>
    </html>
  );
}
